### ISSUE TITLE
3.3 Touchscreen gestures mentions mouseup and touchend, but not click?

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/Mobile-A11y-TF-Note#3]
> Activating elements via the mouseup or touchend event.

I'd say a more robust, input-agnostic piece of advice would be to listen to the `click` event, as it's device-independent (when talking about actual JavaScript events)

**Comment by jspellman** [comment]
Accepted Action-23

**Comment by jspellman** [comment]
done
