### ISSUE TITLE
Preview not displaying under HTTPS

### ISSUE THREAD

**Issue by yatil** [w3c/Mobile-A11y-TF-Note#38]
(this was reported via email to wai-eo-editors@w3.org)

In my console, I get the following notification, so I guess all that is needed to address the issue is to change `http://www.w3.org` to `https://www.w3.org` on external resources

> [blocked] The page at https://w3c.github.io/Mobile-A11y-TF-Note/ was not allowed to run insecure content from http://www.w3.org/Tools/respec/respec-w3c-common.

(I assigned it to everyone who worked on the index.html ever (but @patrickhlauke because it didn’t let me) because I don’t know who’s responsible for making the change :-D)

**Comment by shawna-slh** [comment]
Thanks Eric & Patrick!

Editors listed on doc are @KimPatch @jspellman @kwahlbin 

Would one of y'all merge Patrick's pull request to take care of this? :-)

**Comment by patrickhlauke** [comment]
@nitedog 👍

**Comment by yatil** [comment]
Gracias @patrickhlauke & @nitedog!
